### ISSUE TITLE
Show/Hide on OS X doesn't work properly

### ISSUE THREAD

**Issue by briantanner** [ArsenArsen/KShare#1]
When selecting Show/Hide, the UI does hide, however KShare is still the active application.
When switching to another application, and selecting show again, it does not bring KShare into focus, but does show, in the background.

**Comment by ArsenArsen** [comment]
Could you test against a1ef15c.
I have confirmed this issue occurs on X too.

**Comment by ArsenArsen** [comment]
I've fixed this issue (finally) in 45b1c6f.
Also tested and confirmed the fix. Thanks for the report :)
