### ISSUE TITLE
[Windows] Can't capture

### ISSUE THREAD

**Issue by L1Q** [ArsenArsen/KShare#11]
From the Log:

> KShare - Failed to save picture: Синтаксическая ошибка в имени файла, имени папки или метке тома.

No I dea how to force KShare to log in english :/

Here is an approximate translation:

> KShare - Failed to save picture: Syntactic error in file name, directory name or volume label.

**Comment by ArsenArsen** [comment]
Those errors are reported by your OS. KShare is English only at current time.
What's the Windows name limitation? It sounds like that's the problem.
Try changing the Filename scheme in Settings.

**Comment by L1Q** [comment]
I wish there was a preview of what name/path it tries to create

**Comment by ArsenArsen** [comment]
That's a nice idea. I can do that one day.

`Screenshot %(yyyy-MM-dd HH-mm-ss)date.%ext`

Try this as the scheme. `:` seems reserved in Windows for some reason.

**Comment by L1Q** [comment]
right, 

> :

 is borbidden

**Comment by ArsenArsen** [comment]
I'll keep this open until I change the default name scheme. Thanks for letting me know

**Comment by L1Q** [comment]
np ;D

**Comment by ArsenArsen** [comment]
Fix: 52b6872f8561be83f7c245b560748a37c8c60360
