### ISSUE TITLE
Random recording crash

### ISSUE THREAD

**Issue by L1Q** [ArsenArsen/KShare#15]
There is a heisenbug where KShare would crash when trying to record. I could not reproduce it in any subsequent tries after recording it once ([link](https://dl.dropboxusercontent.com/s/lr385krkxx1n4an/2017-07-04_22-55-12_ns.mp4))

**Comment by ArsenArsen** [comment]
I could not reproduce this in about 20 tries. If you get some more clear reproduction steps they would be rather useful.

NOTE: I was testing on Linux.
~~My VM is still getting it's stuff ready~~

**Comment by L1Q** [comment]
I mean it looks super sneaky. _Maybe_ it has something to do with interacting with preview window?

**Comment by ArsenArsen** [comment]
Huh
I did not think of that. I'll try
~~My VM is having trouble even trying to record >.> It won't even ask me for an area selection dialog~~

**Comment by ArsenArsen** [comment]
It does not seem like it (again, under Linux at least). I just tried.

**Comment by ArsenArsen** [comment]
Ok, yes, I can reproduce it. I'll look into it

**Comment by ArsenArsen** [comment]
I cannot reproduce anymore with the appveyor build.

**Comment by ArsenArsen** [comment]
This has not had any updates in a while, closing
