### ISSUE TITLE
Secondary instances of KShare can crash on quitting

### ISSUE THREAD

**Issue by L1Q** [ArsenArsen/KShare#16]

**Comment by ArsenArsen** [comment]
Could you run the secondary instance from cmd and post the output. I think it's a QHotkey bug with unregistering hotkeys of another process (possible, if you have hotkeys).

**Comment by ArsenArsen** [comment]
Also, I am labeling it as [windows] as I cannot reproduce on Linux.

**Comment by L1Q** [comment]
I think I don't have any hotkeys and when running from cmd it does not return any output to cmd.

**Comment by ArsenArsen** [comment]
Hmm.
I'll try and reproduce this on my Windows VM

**Comment by L1Q** [comment]
Correction: it's not rly happening every time, but one of secondary instances would crash

**Comment by ArsenArsen** [comment]
Yes, I can reproduce this.

**Comment by ArsenArsen** [comment]
![](http://i.imgur.com/HQ9LEqZ.png)

guhhh what

**Comment by ArsenArsen** [comment]
Closing as there has been no new updates for a while.
