### ISSUE TITLE
[Windows] Trying to record a GIF says "File already exists"

### ISSUE THREAD

**Issue by binaryoverload** [ArsenArsen/KShare#18]
Build #204 CI version of KShare, fresh out the box

![screenshot_2](https://user-images.githubusercontent.com/15330699/27994974-03538bac-64bf-11e7-8343-044e6b5f35b7.png)
![screenshot_3](https://user-images.githubusercontent.com/15330699/27994975-03587496-64bf-11e7-9685-88be86bd9f01.png)

Reproduced 3 times by:
 - Setting Record Format to GIF
 - Setting Destination to `Clipboard`
 - Going to Recording -> Start
 - Record for about 1-2 secs
 - Stop Recording

**Comment by ArsenArsen** [comment]
I can't reproduce this. What's your filename scheme?

**Comment by binaryoverload** [comment]
`Screenshot %(yyyy-MM-dd HH-mm-ss)date.%ext`

**Comment by ArsenArsen** [comment]
I managed to reproduce, and actually should've fixed it. Try it eeh?

**Comment by ArsenArsen** [comment]
Managed to reproduce, managed to fix.
