### ISSUE TITLE
Area Screenshot does not work properly on OS X

### ISSUE THREAD

**Issue by briantanner** [ArsenArsen/KShare#2]
1. When taking an area screenshot (on retina), it goes full screen with a lower screen resolution.
2. When pressing escape, the fullscreen goes black, staying in fullscreen until exiting KShare.

https://cdn.discordapp.com/attachments/172142599296122880/307997832542158849/unknown.png

**Comment by ArsenArsen** [comment]
I've in theory fixed this issue as well in 5cc16b4 and someone has tested it for me on a Mac machine. Thanks anyway!
