### ISSUE TITLE
Not authoritively in imgur

### ISSUE THREAD

**Issue by safocl** [ArsenArsen/KShare#23]
autorizovany in imgur, click OK, then make a screenshot, but uploading is not happening
pin code get normally on the website

**Comment by safocl** [comment]
looks like I found the problem "access=" and "refresh=" identical in configuration file

**Comment by ArsenArsen** [comment]
This issue existed, and I fixed it in a commit. Not sure which branch, let me dig it up.

**Comment by ArsenArsen** [comment]
As visible, this works for me on `dev`: 

![](http://i.imgur.com/ygGvDVE.png)

**Comment by safocl** [comment]
[https://i.imgur.com/4JHpNLG.png](url)

**Comment by ArsenArsen** [comment]
Yes, I see that. Try with dev perhaps? It has some other OAuth fixes too

**Comment by safocl** [comment]
Yes, the git version worked fine, thank you

**Comment by ArsenArsen** [comment]
No problem! Thank you for taking the time to open an issue :)
