### ISSUE TITLE
Add to AlternativeTo

### ISSUE THREAD

**Issue by TheDeadCode** [ArsenArsen/KShare#25]
Hey, since it's against the ToS of AlternativeTo to add a software not owned by myself, is it possible to add your software to this list? http://alternativeto.net/software/sharex/?platform=mac

This should make you gain quite a bit of traction with this project. Cheers!

**Comment by ArsenArsen** [comment]
I've already added it, actually: https://alternativeto.net/software/kshare/

**Comment by TheDeadCode** [comment]
Oh my, thank you!
