### ISSUE TITLE
[Question] OSX

### ISSUE THREAD

**Issue by TheDeadCode** [ArsenArsen/KShare#26]
Hey, does this work on OSX? 

I see you didn't release an OSX version, is it because you do not have an Apple Signing Certificate?

**Comment by ArsenArsen** [comment]
The reason was me not having a Mac OS CI, which I did, then our raid failed, and now we are remaking it. Anyway, there are some builds but the CI and the Mac OS node for the CI are down currently. :(

Oh and no I have no certificate

**Comment by TheDeadCode** [comment]
Yeah... Having a Mac OS Server pipeline can be a ***** sometimes... It's hard to make an infrastructure autoscale when you have a static element part of it...

**Comment by TheDeadCode** [comment]
Edit: I could probably sign it. Interested?

**Comment by ArsenArsen** [comment]
I'd rather use my own signature, sorry, but I wouldn't mind help with automating and setting up the entire process. If you happen to have Discord join: https://discordapp.com/invite/Vu8WNTw or if you're more of an IRC guy join irc://irc.snoonet.org/%23Arsen if you don't mind, so I can talk to you there.

Thanks

**Comment by TheDeadCode** [comment]
Joined.
