### ISSUE TITLE
URL's are broken.

### ISSUE THREAD

**Issue by Aetheryx** [ArsenArsen/KShare#29]
http://i.imgur.com/eOHgwSo.png
For both ubuntu and ubuntu-dev :(

**Comment by ArsenArsen** [comment]
I've actually fixed this a minute before you opened the question, but because links for stable Ubuntu and Mac are still down, only development works. Here you go https://nativeci.arsenarsen.com/job/KShare%20(dev)/main=linux/lastSuccessfulBuild/artifact/packages/simpleName.deb

**Comment by Klocko** [comment]
Hi, where's the Windows link?

**Comment by ArsenArsen** [comment]
Here you go. https://ci.appveyor.com/project/ArsenArsen/kshare

My OS X VM is still unrecoverable after all this time :(

**Comment by Aareon** [comment]
@Klocko if your issue has been resolved by using the development version, please close 😄

**Comment by ArsenArsen** [comment]
https://nativeci.arsenarsen.com/job/KShare%20(dev)/
https://ci.appveyor.com/project/ArsenArsen/kshare
