### ISSUE TITLE
All screenshots are black

### ISSUE THREAD

**Issue by YaManicKill** [ArsenArsen/KShare#34]
Hi there,

I'm currently trying to set this up, and it seems to be working apart from the fact that all the screenshots I take are black. I'm wondering if this is something that you have come across before?

I'm running fedora 25.

**Comment by ArsenArsen** [comment]
I assume you're on GNOME, Wayland

Wayland is not supported due to it's permission setups which disallow screenshotting. Until wayland  is not a clustered mess I will not be able to do anything about it

Sorry :/

**Comment by YaManicKill** [comment]
> I assume you're on GNOME, Wayland

Aha, that explains it. I have switched to Xorg and it works.

Thanks for this. Maybe worth adding a "Doesn't work with wayland" somewhere in the readme. 

Thanks for your work, this is a great product.

**Comment by ArsenArsen** [comment]
Thank you for reporting and feedback!
