### ISSUE TITLE
Disable 'Content-Type' header

### ISSUE THREAD

**Issue by YaManicKill** [ArsenArsen/KShare#35]
Quick question, is it possible to turn off the `Content-Type` header for a custom uploader?

Long story short, the uploader I'm currently using crashes if you send it `multipart/form-data` as the `Content-Type`, but works perfectly fine if you send the same request without the header. (see DerEnderKeks/Yanius#31).

I know this is quite a niche thing to ask for, but is it possible to turn off the header?

**Comment by ArsenArsen** [comment]
The multipart standard requires a multipart/* content type header which holds the boundary; eg: `Content-Type: multipart/form-data; boundary=---------------------------00a2d2ad25dsd2ad2asdas3`
So no, disabling this header is not possible.

**Comment by YaManicKill** [comment]
Hmmm yeah, you are right. Ok, I guess this issue is unnecessary then. Still odd that this doesn't work with yanius though.
