### ISSUE TITLE
macOS ETA?

### ISSUE THREAD

**Issue by ItsPugle** [ArsenArsen/KShare#39]
Hey,

I was just wondering what the general ETA is until a macOS Stable Build for KShare?

Cheers!

**Comment by ArsenArsen** [comment]
I still have no macos server to run a VM for compilation on. If someone can figure out travis to build and save artifacts somewhere I'd appreciate.

**Comment by ItsPugle** [comment]
I have literally no idea what that means since I'm not a real developer, but that sounds shitty.

**Comment by ArsenArsen** [comment]
Closing this.
