### ISSUE TITLE
Anonymous uploads on imgur?

### ISSUE THREAD

**Issue by jaltek** [ArsenArsen/KShare#41]
Hi,

I just tried KShare and it seems that the "imgur" is set as the default location. So I accidentally anonymously uploaded an image to imgur? Or isn't this possible without authorization?

The GUI tells "Uploaded to imgur!" but doesn't provide a link...

**Comment by ArsenArsen** [comment]
The link is copied to your clipboard. Without authorization is default, double clicking the imgur item will ask you for credentials.

**Comment by jaltek** [comment]
Ok any chance to get the image by the pre-defined client-id or something as I didn't have the link in the clipboard anymore?

**Comment by ArsenArsen** [comment]
What do you mean? Everything works fine by default. And it does anonymous uploads by default with my own client-id

**Comment by jaltek** [comment]
Do you have access to the images uploaded by your client-id? The image I accidentally uploaded should not be visible in imgur :\

**Comment by ArsenArsen** [comment]
OH no I do not.

**Comment by jaltek** [comment]
Well, sure - it was my fault but maybe you should consider the following points:
a.) Not uploading images to imgur as default destination
b.) Maybe storing the URLs to a logfile or something.
c.) Also saving the "delete hash" of an uploaded image in order to delete it afterwards

**Comment by ArsenArsen** [comment]
Let me address these points:
1. The whole purpose IS to upload and copy the links
2. This feature is implemented in ``dev``
3. This cannot be implemented because I cannot delete images anonymously uploaded.

**Comment by jaltek** [comment]
1.) Well - IMHO you should put this in the Readme that this is the default. This wasn't clear to me honestly.
2.) perfect.
3.) IMHO you can: https://api.imgur.com/endpoints/image/#image-delete. All you need is the "delete hash" which is returned by the API in the JSON result after the upload. With this hash you should be able to delete the image.

**Comment by ArsenArsen** [comment]
Not all uploaders have this. Plus you could do this yourself. The Client ID is in the source code. 

https://apidocs.imgur.com/#561fa33f-1d43-636a-57bd-8cdc22e13e47

**Comment by jaltek** [comment]
What do you mean? I am not able to delete an image only with the Client ID. What I need is the "deletehash" from the image itself which is returned by the JSON API after the successful upload.
So - if you also put this information also the logfile one will be able to delete anonymously uploaded images.

Example:
```
{
  "data": {
    "id": "orunSTu",
    "title": null,
    "description": null,
    "datetime": 1495556889,
    "type": "image/gif",
    "animated": false,
    "width": 1,
    "height": 1,
    "size": 42,
    "views": 0,
    "bandwidth": 0,
    "vote": null,
    "favorite": false,
    "nsfw": null,
    "section": null,
    "account_url": null,
    "account_id": 0,
    "is_ad": false,
    "in_most_viral": false,
    "tags": [],
    "ad_type": 0,
    "ad_url": "",
    "in_gallery": false,
    "deletehash": "x70po4w7BVvSUzZ",
    "name": "",
    "link": "http://i.imgur.com/orunSTu.gif"
  },
  "success": true,
  "status": 200
}
```

**Comment by ArsenArsen** [comment]
Oh. dev does.

**Comment by jaltek** [comment]
Well then I better had used the dev branch 😆 
Perfect. Nevertheless, thank you for the fast support 👍
