### ISSUE TITLE
Change the location of bianries

### ISSUE THREAD

**Issue by Suleman-Elahi** [ArsenArsen/KShare#43]
Link to the binaries is always broken. Every time I go to download EXE or DEB there is 404. At least place them on Google Drive, DropBox, etc....

**Comment by ArsenArsen** [comment]
Dev builds:
https://nativeci.arsenarsen.com/job/KShare%20(dev)/
https://ci.appveyor.com/project/ArsenArsen/kshare/

Former: dev branch, I didn't update them because I have no done release.
Latter: good way to waste my time and kill automation.

Duplicate of #29
