### ISSUE TITLE
Blank Screenshot !!!

### ISSUE THREAD

**Issue by Suleman-Elahi** [ArsenArsen/KShare#44]
Whenever I do a screenshot, it saves a black image with the cursor only. I am currently running KShare on  Ubuntu 17.10

**Comment by ArsenArsen** [comment]
This is most likely caused by Wayland. There is (and will be) no Wayland support in the near future. These are some ways to confirm Wayland is running 
```bash
echo $XDG_SESSION_TYPE
ps aux | grep wayland # some stuff like GNOME have --wayland flags
loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type # shows session type, possibly most reliable for systemd systems
```
