### ISSUE TITLE
It does not start

### ISSUE THREAD

**Issue by safocl** [ArsenArsen/KShare#51]
It does not start, it simply does not output any output in the terminal.
no messages appear in the "journalctl -f".

`````
--> screenfetch 
                   -`                 
                  .o+`                 safff@nout
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 4.14.6-1-ARCH
               `+oooooo:               Uptime: 37m
               -+oooooo+:              Packages: 1363
             `/:-:++oooo+:             Shell: zsh 5.4.2
            `/++++/+++++++:            Resolution: 1920x1080
           `/++++++++++++++:           WM: i3
          `/+++ooooooooooooo/`         GTK Theme: Breeze-Dark [GTK2/3]
         ./ooosssso++osssssso+`        Icon Theme: Adwaita
        .oossssso-````/ossssss+`       Font: Liberation Sans 11
       -osssssso.      :ssssssso.      CPU: Intel Core i3-2350M @ 4x 2.3GHz [49.0°C]
      :osssssss/        osssso+++.     GPU: intel
     /ossssssss/        +ssssooo/-     RAM: 2184MiB / 7893MiB
   `/ossssso+/:-        -:/+osssso+-  
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/
 .`                                 `/
```
`

**Comment by ArsenArsen** [comment]
Known issue I'm working on right now.

**Comment by safocl** [comment]
it seems with some kind of update, on the main computer for a long time did not update, but here I put it, I thought already that it was something that happened to me

**Comment by ArsenArsen** [comment]
Yes, it's the lock file. I'm making it work differently.

**Comment by ArsenArsen** [comment]
Rolled out a temporary fix. Turns out this is not as trivial as I expected it to be

**Comment by SilverMight** [comment]
The application now launches for me but can not take area or fullscreen screenshots, only active window.

Verbose has nothing to say other than:
` 
DEBUG: lol
`

**Comment by ArsenArsen** [comment]
Can you post your settings file @SilverMight after you remove all identifying/sensitive informaton?

**Comment by SilverMight** [comment]
`[General]
delay=0
hotkey_area=Ctrl+Shift+$
hotkey_recordingstart=Ctrl+Shift+%
magnifierPixelCount=15
quickMode=true
saveLocation=1
uploader=ratelimited

[command]
fullscreenCommand=0

[recording]
format=0
framerate=30

[screenareaselector]
rect=@Rect(8 268 1062 772)
`
Haven't changed anything since last update @ArsenArsen

**Comment by ArsenArsen** [comment]
Go into your settings and empty out the Fullscreen capture command field

**Comment by SilverMight** [comment]
Thanks, that worked.

**Comment by ArsenArsen** [comment]
Going to make that auto clear and re-run as the default provider in a bit. Didn't consider this edge case while making that.

**Comment by safocl** [comment]
I confirm - everything works.

**Comment by ArsenArsen** [comment]
Closing this - it was resolved.
