### ISSUE TITLE
.deb link leads to 404

### ISSUE THREAD

**Issue by Trophonix** [ArsenArsen/KShare#53]
The "Ubuntu .deb" link goes to a 404 page: https://nativeci.arsenarsen.com/job/KShare%20Stable/lastSuccessfulBuild/artifact/packages/simpleName.deb

**Comment by jellz** [comment]
and the proper link doesn't even download.

**Comment by ArsenArsen** [comment]
Duplicate of #29

Read the last comment

**Comment by Trophonix** [comment]
That doesn't solve the issue, though.. you need to change the links in the readme, not just wait for people to ask and then link them to the correct link

**Comment by ArsenArsen** [comment]
I added a note but I won't be updating the links until a release because I don't have links which are up and running other than the development ones.
