### ISSUE TITLE
Suggestion: Start kshare minimized mode

### ISSUE THREAD

**Issue by RaymondSchnyder** [ArsenArsen/KShare#62]
Hello,

I would like to ask if its possible to make an option which lets kshare start minimized without opening the gui.
Because i find it a little bit annoying when everytime my tilling desktop starts kshare tries to take half of the screen.
Then i have to do a rightclick on the icon in the taskbar to minimize it. 
Maybe its already there and i didnt found it?

Also sorry for my english, i hope its atleast understandable.

EDIT: In the wiki under basic usage on the first sentence you say that there are arguments to start kshare with, but there arent documented as far as i can see.

**Comment by ArsenArsen** [comment]
The wiki will be getting a full rewrite, when I stop being busy with life, and this option is revealed as `--background` by `--help`. Thanks for asking :)
