### ISSUE TITLE
Sometimes keybinds just, don't work 

### ISSUE THREAD

**Issue by theLMGN** [ArsenArsen/KShare#63]
Randomly keybinds just wont work and give me The Ding every time I press my keybind button.

KShare 4.1

Ubuntu Budgie 17.10

Budgie Version: 10.4-1ubuntu4

**Comment by ArsenArsen** [comment]
There's multiple possible causes for this: first, the bind is already taken, second, Wayland.
Try to run the program from inside a console and check it's output.

Cannot reproduce.

**Comment by theLMGN** [comment]
It just randomly stops working and I have to restart KShare

``` thelmgn  ~  1   kshare
Gtk-Message: Failed to load module "canberra-gtk-module"```

**Comment by ArsenArsen** [comment]
Okay, so it's not the binds being taken. Are you running Wayland?

**Comment by theLMGN** [comment]
Don't think so. Is there anyway to check?

**Comment by Cknight70** [comment]
I can confirm I had this problem, but it was because KDE was using the shortcut (I think KDE spectacle). If I remember Ubuntu defaults to using Wayland if you don't have an Nvidia graphics card. I believe you can check though by typing 
`echo $XDG_SESSION_TYPE`

**Comment by theLMGN** [comment]
@Cknight70 Ah, I'm not using Wayland then

```
 thelmgn  ~  echo $XDG_SESSION_TYPE
x11
```

**Comment by ArsenArsen** [comment]
Weird.. I still cannot reproduce it though, and I haven't had another case of it. Check is the keybind taken already?

**Comment by theLMGN** [comment]
Ah, my distro had it bound to Save screenshot to pictures by default.

**Comment by ArsenArsen** [comment]
Well, that solves it.
