### ISSUE TITLE
So I think I possibly might have found your CI issue

### ISSUE THREAD

**Issue by GlitchMasta47** [ArsenArsen/KShare#64]
![Screenshot](http://curb.my-me.me/oaimcm.png)
Either I don't have access to see it or your KShare stable job isn't anywhere to be found.

**Comment by ArsenArsen** [comment]
There isn't one because the CI died and it would be quite pointless to do a recovery

**Comment by GlitchMasta47** [comment]
M'kay. Do I just... Because I'm on Windows now, so... Download? Where are you hiding?

**Comment by ArsenArsen** [comment]
https://ci.appveyor.com/project/ArsenArsen/kshare/
