### ISSUE TITLE
Suggestion: Add option to disable local file saving

### ISSUE THREAD

**Issue by linkjay** [ArsenArsen/KShare#65]
Simple enough. I'm uploading my gifs via a custom post config to my website. If you setup a static file name on the "File name scheme", you get an error that the file already exists which is to be expected. 

However, I have no reason to store images on my hard drive since I have a webserver to handle that for me. Therefore, I think there should be an option to disable saving locally.

**Comment by ArsenArsen** [comment]
Honestly I have no idea how I forgot to add this. Thanks for the reminder.

**Comment by linkjay** [comment]
You the man! Thanks for this.

Found KShare in my seemingly, at the time, futile search for an alternative to the Windows PicPick. I finally discovered your application which allowed everything I wanted, including POST uploads. Good project! However, I digress.

Issue closed.
