### ISSUE TITLE
Option for multiple monitors?

### ISSUE THREAD

**Issue by stagskin** [ArsenArsen/KShare#7]
By default you're only able to take screenshots of your primary monitor. It'd be nice if you had the option to choose which monitor the screenshot should be taken of.

**Comment by ArsenArsen** [comment]
I am getting a new monitor in order to properly implement multi-screen support, and because I need it.

Anyway, yes, currently it doesn't work, but I'm starting to implement it some time this week, when it arrives.

**Comment by ArsenArsen** [comment]
Could you test the latest `dev` branch build?

**Comment by lclc98** [comment]
Multimonitor works for screenshots, but not color picking

**Comment by ArsenArsen** [comment]
I knew I forgot something... What about different resolution monitors @lclc98

**Comment by ArsenArsen** [comment]
After this has been given a good amount of testing by me, @lclc98, and a few more people we can confirm the fix works perfectly fine. 

Thanks :)
