### ISSUE TITLE
Unable to find file for inclusion

### ISSUE THREAD

**Issue by watercolorhearts** [ArsenArsen/KShare#74]
While trying to install this on Linux Mint Cinnamon 18.3 I get this error

u@u-desktop ~/Downloads/Programs/KShare $ qmake-qt4
WARNING: /home/u/Downloads/Programs/KShare/KShare.pro:157: Unable to find file for inclusion QHotkey/qhotkey.pri
Project ERROR: Package libavformat not found

How do I fix it?

**Comment by ArsenArsen** [comment]
* Use qmake-qt5
* Install `lib{avformat,avcodec,avutil,swscale}-dev`
* `git submodule update --init --recursive`
