### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by linkjay** [ArsenArsen/KShare#75]
When trying to open KShare, I get this error. I am using the latest GitHub build for kshare-git that the aur provides.

`kshare: error while loading shared libraries: libswscale.so.4: cannot open shared object file: No such file or directory`

Using the latest Arch Linux.

It seems like this is an ffmpeg library error? I've installed like 10 different ffmpeg from the repos and the aur and still can't get this to work.

**Comment by ArsenArsen** [comment]
rebuild the package.

**Comment by linkjay** [comment]
Huh, alright. I'm not sure why my aur helper yay doesn't do this by default. 

It's all fixed now. Thank you.
