### ISSUE TITLE
Add a tray icon

### ISSUE THREAD

**Issue by Cknight70** [ArsenArsen/KShare#76]
![image](https://user-images.githubusercontent.com/28763729/41196258-3f86711a-6bf9-11e8-9d83-35a9e847cdbd.png)

Because it doesn't have one.

(I'm using Plasma 5.12 on Arch)

**Comment by ArsenArsen** [comment]
It absolutely does.  
![image](https://user-images.githubusercontent.com/7805050/41196307-f2765662-6c3c-11e8-9bda-9730324553ef.png))  
Keep in mind to move future issues to https://gitlab.com/ArsenArsen/KShare as soon I will be moving everything there.
