### ISSUE TITLE
[Windows] Multimonitor does not work in negative coordinate space

### ISSUE THREAD

**Issue by L1Q** [ArsenArsen/KShare#9]
In my 3 monitor setup I have my center monitor as main.
The left one is ingored by KShare cmpletely.

**Comment by ArsenArsen** [comment]
Try setting the editor offset in Settings. It might be the problem.

**Comment by L1Q** [comment]
It helps cover the left screen but now the right one is missing

**Comment by ArsenArsen** [comment]
It seems like the geometries are off. I'll try to figure how to compile KShare on Windows without cross compiling to try and debug this. Thanks for letting me know.

**Comment by ArsenArsen** [comment]
Can you test the fix?

**Comment by L1Q** [comment]
What's the best way to get binary? latest from CI does this weird thing
![captured with KShare](http://i.imgur.com/pYVRM0L.png)
in comparison my whole desktop captured with ShareX
![captured with ShareX](https://dl.dropboxusercontent.com/s/65qsb0syrd4vczn/2017-07-05_17-59-44.jpg)

well, at least the geometry is fixed, right?

**Comment by ArsenArsen** [comment]
When I compile and run from within a VM I get good results. 
![](http://i.imgur.com/VgFDOoj.png)

I have a feeling the CI produces bad executable at this point. I'll try with AppVeyor later.

**Comment by ArsenArsen** [comment]
Use the AppVeyor build from now on.
